#### Definition of the size of the memory pool

## TIP1: It can make sense to test small pool sizes to test corner cases where an allocation would fail

## TIP2: Some programs (such as 'ps') require allocating large memory blocks. Increase the size of the pool to handle such cases (for instance, giving a size of 10485760 (10MB))

#MEMORY_SIZE=1024   
MEMORY_SIZE=10485760   
#MEMORY_SIZE=150   

#### Definition of the allocation policy

## possible values are FF, BF, WF and NF

ALLOC_POLICY=BF


#### Definition of the memory allignment constraint

MEM_ALIGNMENT=1
